# Generated by Django 5.2.8 on 2025-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoringConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("urgency", models.FloatField(default=1.5)),
                ("importance", models.FloatField(default=2.0)),
                ("effort", models.FloatField(default=1.2)),
                ("dependencies", models.FloatField(default=1.8)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="task",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="task",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(blank=True, to="tasks.task"),
        ),
    ]
